version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    ports:
      - "127.0.0.1:4317:4317" # OTLP gRPC receiver
      - "127.0.0.1:4318:4318" # OTLP HTTP receiver
      - "127.0.0.1:55679:55679" # ZPages extension
    network_mode: "host"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
